FROM openjdk:11
COPY target/MicroService_Categories_Skills-0.0.1-SNAPSHOT.jar /MicroService_Categories_Skills-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/MicroService_Categories_Skills-0.0.1-SNAPSHOT.jar"]